import TheFooter from "@/components/TheFooter";
import TheHeader from "@/components/TheHeader";
import type { Metadata } from "next";
import localFont from "next/font/local";
// import './style/style.scss'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next App", //title тоесть имя страници 
  description: "Generated by create next app", //это meto теги
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TheHeader/>

        <main className="container">
          {children}
        </main>

        <TheFooter/>
      </body>
    </html>
  );
}
